### ISSUE TITLE
Rethink Lightning Talks

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#157]
The Lightning talks usually consist of multiple talks by different speakers about different topics. I think we should split up the lightning talks video into multiple individual "talks" on RubyVideo. A few reasons:

* Summaries are not gonna be accurate
* The Tags/Topics are not going to represent well what all the people talked about
* As a user you never see the lightning talk titles, so you don't know what you get.
* As a user you would never just click on a "Lightning Talks" talk on RubyVideo and say "let me watch all lightning talks"
 
But instead, if they were shown as individual talks you might end up clicking on one of them. Blue Ridge Ruby and Helvetic Ruby published individual videos for each of the lightning talks, but if an event doesn't do that, we could do it.

For the Euruko 2019 lightning talks we currently have something like:

```yaml
- title: Lightning Talks
  raw_title: Lightning Talks
  speakers:
    - Madison White # Super-powering your editor with Sorbet Typer
    - Miriam Tocino # Zerus & Ona
    - Julik Tarkhanov # NoSuchBucket
    - Benjamin Vetter # search_flip
    - Norma Miller # A "Splash" Course on Live Captioning
  event_name: Euruko 2019
  published_at: "2021-06-01"
  description: ""
  video_id: 2-1wlXkLt-I
```

But it would be better is if we had something like this instead:

```yaml
- title: Lightning Talks
  raw_title: Lightning Talks
  event_name: Euruko 2019
  published_at: "2021-06-01"
  description: ""
  video_id: 2-1wlXkLt-I
  talks:
    - title: Super-powering your editor with Sorbet Typer
      raw_title: Super-powering your editor with Sorbet Typer
      speakers: 
        - Madison White
      description: ""
      video_cue_start: 00:00
      video_cue_end: 05:00
      
    - title: Zerus & Ona
      raw_title: Zerus & Ona
      speakers: 
        - Miriam Tocino
      description: ""
      video_cue_start: 05:10
      video_cue_end: 10:00
      
    - title: NoSuchBucket
      raw_title: NoSuchBucket
      speakers: 
        - Julik Tarkhanov
      description: ""
      video_cue_start: 10:10
      video_cue_end: 15:00
      
    - title: search_flip
      raw_title: search_flip
      speakers: 
        - Benjamin Vetter
      description: ""
      video_cue_start: 15:10
      video_cue_end: 20:00
      
    - title: A "Splash" Course on Live Captioning
      raw_title: A "Splash" Course on Live Captioning
      speakers: 
        - Norma Miller
      description: ""
      video_cue_start: 20:10
      video_cue_end: 25:00
```

So we could index, show and analyze the talks individually. With the cues, we could even just embed only the specific part of the YouTube video.
