### ISSUE TITLE
Ability to link to additional resources

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#447]
I think it would make sense that we could link to additional resources (in addition to the `slides_url`). For linking to a blog post, announcements, GitHub repo with the source code, link to another talk, etc.

Ideally this would just be part of the YAML file, like:

```yaml
- title: Talk Title
  [...] 
  speakers:
    - Speaker Name
    
  additional_resources:
    - name: Source Code
      url: https://github.com/...

    - name: Documentation
      url: https://link.to.documentation/...

    - name: Blog Post
      url: https://link.to.blog.post/...
```
