### ISSUE TITLE
Introduce the concept of "Alternative Recordings"

### ISSUE THREAD

**Issue by marcoroth** [adrienpoly/rubyvideo#579]
Sometimes a talk doesn't get recorded or doesn't get published. But the "same" talk was given at another event we could link to that talk and/or embed the recording of the other event instead.

In the YAML file we could add another optional key for the talk. It could look like this for the José Valim Keynote at EuRuKo 2024:

```yaml
- title: "Keynote: Livebook: where Web, AI, and Concurrency meet"
  raw_title: "Keynote: Livebook: where Web, AI, and Concurrency meet"
  event_name: EuRuKo 2024
  date: "2024-09-12"
  published_at: "2025-01-13"
  speakers:
    - José Valim
  description: "..."
  video_id: jose-valim-euruko-2024
  video_provider: not_recorded
  alternative_recordings:
    - title: "Livebook & Elixir: Where AI, Web & Concurrency Meet"
      event_name: "YOW. 2023"
      date: "2023-12-08"
      video_provider: youtube
      video_id: "pas9WdWIBHs"
      external_url: https://yowcon.com/sydney-2023/sessions/2758/livebook-and-elixir-where-ai-web-and-concurrency-meet
```
